name: chesstorch
channels:
  - defaults
dependencies:
  - pytorch::pytorch
  - torchaudio
  - torchvision
  - conda-forge::ultralytics

# do conda config --append channels conda-forge before running conda env create -f environment.yml